* SBNRR是用来做什么的？ #card #正念
:PROPERTIES:
:card-last-interval: 39.41
:card-repeats: 4
:card-ease-factor: 2.9
:card-next-schedule: 2022-11-06T09:18:57.499Z
:card-last-reviewed: 2022-09-28T00:18:57.499Z
:card-last-score: 5
:END:
** Use The ‘SBNRR’ Technique To Handle Stressful Moments Mindfully
*** 助记词：傻笨难容人
* SBNRR的步骤是什么？ #card #正念
:PROPERTIES:
:card-last-interval: 13.91
:card-repeats: 3
:card-ease-factor: 2.86
:card-next-schedule: 2022-11-13T22:20:55.976Z
:card-last-reviewed: 2022-10-31T01:20:55.976Z
:card-last-score: 5
:END:
** Stop
*** This is the most important step. Instead of becoming wrapped up in the emotion or making an impulse decision, ^^just stop^^. Decide to take a moment.
** Breathe
*** Take a ^^deep breath^^. This helps clear your mind, as well as helps physiologically calm down your brain.
** Notice
*** Notice what you’re ^^experiencing^^ on a moment to moment basis. What are you feeling in your body? What emotions are you experiencing? Is it static or is it changing? Does the emotion seem out of proportion compared to the trigger?
** Reflect
*** What’s ^^causing^^ the emotion? Is it the right response? Is a part of you feeling attacked, belittled or threatened? Is there a story to the experience you’re having? Engaging the prefrontal cortex's executive function.
** Respond
*** Think of all the different courses of actions you can take. Consider the ^^kindest^^, most ^^compassionate^^ way to respond to the situation (even if you don’t take that path.) Finally, make a ^^conscious^^ decision on how to respond.