* 理科：
** 公理
** 概念
*** 概念之间的联系
**** 推导
**** 同一
**** 交叉
**** 从属
**** 矛盾
** 概念的用法
*** 什么是用法？演绎？归纳？
**** 对于做题来说，主要是演绎法
**** 三段论
***** 大前提
***** 小前提
***** 结论
**** 所谓“用法”，大概就是各种大前提(公理、定理)的组合，应用于小前提(题目条件)，经过逻辑推理达成结论的过程
***** 所以，记忆各种大前提(公理、定理)，以及他们之前的常见组合非常重要
***** 分析、组合、匹配小前提(题目条件)也很重要
***** “探索法”的本质是这些大前提、小前提之间的匹配模式？
**** 所谓“题型”，大概就是这些常见的匹配模式？
**** 所谓“坑点”，就是常错的地方
***** 但是每个人似乎都不一样？
***** 为什么会踩坑
****** 知识盲点
****** 思维定势
****** 思维局限
****** 习惯和不完善的肌肉记忆
* 构建网络
** 公理、定理
** 性质、推论
** 题目：一个网络
*** 节点：事实/条件
*** 边：公理、定理、性质、推论的代入(类似于函数调用？)
* 理解数学证明
** 阶段一: 理解证明
*** 这一阶段将会涉及到对证明的多次转写. 第一步是把证明分解(graze), 然后从中摘出独立的元素制作成Anki卡片.
:LOGBOOK:
CLOCK: [2022-07-14 Thu 09:52:30]--[2022-07-14 Thu 09:52:31] =>  00:00:01
:END:
*** 我还会很用心的去把这些想法用不同的方式重新表述
*** 你需要的是一个最精简的答案, 要尽可能单刀直入地把核心想法表现出来
*** 采用多种角度去思考"同一个"数学问题的价值是再怎么强调也不为过的
*** 在这个阶段, 你要做的是学会这个证明的方法. 每一个证明中的元素都应成为你的一件称手的"精神家具(mental furniture)", 最好是你开始能真正感受到的东西. 这就意味着要用多种角度理解证明中的每个想法, 并在不同的想法之间找到尽可能多的联系.
*** 欠缺数学经验的人往往会把证明看成一张由命题组成的线性列表, 但更有效地方式是把证明看作一些由基本事实(observation)相互连缀而成的网络. 你要相信能佐证一件事物正确性的证据绝对不会只有一个; 寻找事物的不同面向的解释将会加深你的理解. 虽然从某种意义上说这很"低效", 但这却是加深理解和增强直觉的一种方式. 你在做的是在节点之间建立更多的联系, 构建这个证明的网络.
*** 一种具体方法是去探索一些细微的改动.
*** 提出"合适"的问题, 即富有洞察力的问题, 的能力是整个Anki化过程的中的一个难点, 需要一些数学经验
*** 我一直在描述如何分解证明, 旨在让自己彻底熟悉证明中的每一个元素. 这很有用,但也是一个方向相当不明确的过程: 没有明确的终点, 也不一定能帮助你理解更广泛的证明结构(the broader to structure of the proof). 我给自己设定了一个更理想的目标: 所有的改动都是为了把整个证明"蒸馏"到只剩一个问题和一个(简单的)答案.
*** 我把这些模板问题当成*边界条件*或者*强制函数*(forcing function).它们是我的目标, 我试着写一堆问题来帮助我达成这个目标.
*** 这个过程从分解证明中的元素开始, 但随着时间的推移, 焦点转移到更多关于证明本身的结构性问题, 以及各个元素如何组合在一起的问题.
*** 一般来说, 让问题和答案尽可能*原子化*(atomic)是很有帮助的, 这似乎也有助于提升清晰度. 原子化并不意味着问题和答案不能涉及非常复杂的概念, 但它们最好只表达一个单一的想法.
*** 集中研究一个主题的人逐渐开始建立"组块库"——用来识别和推理的大量模型.
*** 这也是为什么有的顶级棋手可以一步步记住上千个对局的原因. 他们不是记个人的动作——他们只记每局对弈中用模型传递出来的想法. 他们对国际象棋研究得如此之多, 以至于这些想法和模型都很有意义, 就像情人往来书信中的密语.专家们开始思考, 也许这样的组块只是被半意识地使用的, 那些传统的表现形式——数学中的字母或符号, 棋盘上棋子的移动——仍然存在, 但它们在某种程度上是次要的.
*** 当我数学学得很好的时候, 也就是在我前面描述的深度内化状态下, 我主要使用这种更高级的组块, 这就是为什么它不再看起来像是符号, 语言或视觉对象.我没有完全意识到发生了什么——这更多的是一种在各种各样的物体上玩来玩去的感觉, 尝试一些东西, 试图找到意想不到的联系. 但是, 据推测这个过程的底层机制就行心理组块.
*** 我找到的唯一可靠的去进入这种状态的方法就是痴迷于一些数学问题.
*** 但我注意到, 当我进行Anki化过程时, 我也开始越来越少依赖这种传统的方式. 似乎我写的问题越多, 模型就越真实. 所以我想知道Anki化过程是否可以作为一种确定性的达到这种状态的方法.
*** 阶段二: 改动, 突破界限
**** 我发现以许多不同的方式来改变定理的假设, 并思考定理什么时候变无效(或能推广)是很有帮助的
**** 另一个好方法是问条件能不能削弱
**** 这个第二阶段实际上是开放式的: 我们可以无止境地进行改动. 提的问题不再直接与原证明有关, 而是以各种方式"戳"原证明, 看看会发生什么事. 思考得越远, 和其他结论的联系越多越好.
*** Anki化过程相当耗费时间. 我没有任何简单的方法来统计我为每个定理中写了多少个问题, 但我猜想每个命题大约有几十张卡片. 这通常需要几个小时, 尽管我希望我可以很容易地添加更多的问题.
**** 以前, 虽然我可以写下正规矩阵可对角化的证明, 但一切都有点模糊. 现在, 它看起来很显然 我几乎可以直接看出它是真的. 当然, 原因是我对所有底层元素以及它们之间的关系变得更加熟悉了.
*** 我觉得最有价值的是Anki带给我的信心
**** 我一定会记住我从这个过程中学到的东西.
**** 与其说是一个个单一的事实, 不如说是一种对数学对象的熟悉和流畅运用的感觉, 以及一种轻松看到它们之间关系的能力.
* 演绎法
** 是以一个或多个命题为起点，通过运用不包含任何实证研究的纯粹逻辑推理，得出与该命题等价的其他命题的过程。
** 演绎：事实A+事实B→结论
** 演绎法要想得出靠谱的结论，需要两个条件：
** 一、起点命题本身必须是靠谱的
** 二、推理的过程中没有逻辑瑕疵
* 归纳法
** 是以一个或多个命题假设为起点，通过实证分析，即观察或实验、收集和分析数据、验证假设，对命题假设进行证实或证伪判断的过程。
** 归纳：结论→规律
* 归纳法和演绎法的区别
** 一、归纳法所需的命题假设，必须是后验的、可以证伪的，而不能是先验/超验的、不可证伪的。
** 二、归纳法使用的是实证分析，而不是逻辑推演。
* 其实就是概率思维。
** 提出一个命题假设，然后通过观察/实验，看事实会在多大程度上符合假设。
** 也就是，符合假设的概率有多大。
*** 如果足够大，大到人们能够高度确信的程度，就成为了“*定律*”。
*** 相对地，演绎法从真命题推导出的结论命题，称作“*定理*”。